name: Publish to PyPI

on:
  push:
    tags:
      - 'v*' # Se déclenche lors du push d'un tag comme v0.3.0

jobs:
  build-n-publish:
    name: Build and publish Python 🐍 distributions 📦 to PyPI
    runs-on: ubuntu-latest
    permissions:
      # Cette permission est CRUCIALE pour le Trusted Publishing (OIDC)
      id-token: write
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install build dependencies
        run: |
          python -m pip install --upgrade pip
          pip install build

      - name: Build binary wheel and source tarball
        run: python -m build

      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          # Pas besoin de mot de passe ou de token ici si Trusted Publishing est configuré
          print-hash: true